# Generated by Django 5.2.4 on 2025-08-28 23:34

import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='store_admin', max_length=10)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('store_id', django_mongodb_backend.fields.ObjectIdField(default='64e63c52f1a743f8bdcd91ab')),
                ('Title', models.CharField(blank=True, max_length=120)),
                ('product_name', models.CharField(max_length=100)),
                ('product_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('isResolved', models.BooleanField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.CharField(max_length=50)),
            ],
        ),
    ]
