# Generated by Django 5.2.4 on 2025-07-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='store_admin', max_length=10)),
                ('contact', models.IntegerField(max_length=12)),
            ],
        ),
    ]
