# Generated by Django 5.2.4 on 2025-08-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tickets',
            name='store',
            field=models.JSONField(default=list),
        ),
    ]
