# Generated by Django 5.2.4 on 2025-08-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_review_product_store_tickets_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='review',
            new_name='reviews',
        ),
    ]
