# Generated by Django 5.2.4 on 2025-07-20 18:22

import datetime
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_url', models.CharField(max_length=100)),
                ('sentiment', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=150)),
                ('reviewer_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 7, 20, 18, 22, 18, 418594, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(default='Indore', max_length=100)),
                ('revenue', models.FloatField(max_length=150, null=True)),
                ('customers', models.IntegerField(max_length=100, null=True)),
                ('employees', models.IntegerField(max_length=100)),
                ('rating', models.FloatField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('isResolved', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 7, 20, 18, 22, 18, 418212, tzinfo=datetime.timezone.utc))),
                ('priority', models.CharField(max_length=50)),
            ],
        ),
    ]
