# Generated by Django 5.2.4 on 2025-08-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_review_product_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store_id',
        ),
    ]
