# Generated by Django 5.2.4 on 2025-07-20 19:30

import datetime
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_store_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 19, 30, 26, 625925, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 19, 30, 26, 625520, tzinfo=datetime.timezone.utc)),
        ),
    ]
