# Generated by Django 5.2.4 on 2025-08-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Title',
        ),
    ]
