# Generated by Django 5.2.4 on 2025-08-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='five_star',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='four_star',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='one_star',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='three_star',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='two_star',
            field=models.IntegerField(null=True),
        ),
    ]
