# Generated by Django 5.2.4 on 2025-07-21 04:21

import datetime
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_title_alter_product_date_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_id',
            field=django_mongodb_backend.fields.ObjectIdField(default='64e63c52f1a743f8bdcd91ab'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 21, 4, 21, 30, 894644, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 21, 4, 21, 30, 893409, tzinfo=datetime.timezone.utc)),
        ),
    ]
