# Generated by Django 5.2.4 on 2025-07-22 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_store_id_alter_product_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 19, 36, 10, 278553, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='store',
            name='customers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='employees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='revenue',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 19, 36, 10, 277957, tzinfo=datetime.timezone.utc)),
        ),
    ]
