# Generated by Django 5.2.4 on 2025-07-23 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customuser_contact_alter_product_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 4, 31, 9, 915154, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 4, 31, 9, 913886, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='isResolved',
            field=models.BooleanField(max_length=10),
        ),
    ]
